from __future__ import annotations

import json
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_DIR / "data" / "curated_places.json"


def weekly(**days):
    return {
        day: days.get(day)
        for day in ("mon", "tue", "wed", "thu", "fri", "sat", "sun")
    }


EXPANSION = [
    {
        "id": "st-anns-warehouse",
        "name": "St. Ann's Warehouse",
        "category": "Performance & Music",
        "venue_type": "International performing arts venue",
        "borough": "Brooklyn",
        "neighborhood": "DUMBO",
        "address": "45 Water Street, Brooklyn, NY 11201",
        "latitude": 40.703665,
        "longitude": -73.992959,
        "description": "A waterfront theater presenting international theater, music, and ambitious interdisciplinary productions inside the historic Tobacco Warehouse.",
        "website": "https://stannswarehouse.org/",
        "events_url": "https://stannswarehouse.org/",
        "program_label": "Current productions",
        "schedule_type": "event",
        "hours_label": "Open for scheduled performances; the box office opens around performance times",
        "admission_label": "Tickets are priced by production; recent mainstage tickets have started around $55",
        "visit_source": "https://stannswarehouse.org/about-st-anns-warehouse/contact-us/",
    },
    {
        "id": "tfana-polonsky",
        "name": "Polonsky Shakespeare Center",
        "category": "Performance & Music",
        "venue_type": "Classical and contemporary theater",
        "borough": "Brooklyn",
        "neighborhood": "Fort Greene",
        "address": "262 Ashland Place, Brooklyn, NY 11217",
        "latitude": 40.687446,
        "longitude": -73.978796,
        "description": "Theatre for a New Audience's flexible Brooklyn home for Shakespeare, classic drama, contemporary reinterpretations, talks, and workshops.",
        "website": "https://tfana.org/",
        "events_url": "https://tfana.org/current-season",
        "program_label": "Current season",
        "schedule_type": "event",
        "hours_label": "Open for scheduled performances; will call begins one hour before curtain",
        "admission_label": "Full-price productions are commonly $95; $20 New Deal tickets for full-time students and visitors 30 or under",
        "adult_price": 95,
        "student_price": 20,
        "under_25_price": 20,
        "visit_source": "https://tfana.org/current-season/20-new-deal-tickets",
    },
    {
        "id": "brick-theater",
        "name": "The Brick",
        "category": "Performance & Music",
        "venue_type": "Artist-centered experimental theater",
        "borough": "Brooklyn",
        "neighborhood": "Williamsburg",
        "address": "579 Metropolitan Avenue, Brooklyn, NY 11211",
        "latitude": 40.714299,
        "longitude": -73.949742,
        "description": "A nonprofit incubator for emerging and experimental theater, dance, film, performance art, and cross-disciplinary work.",
        "website": "https://www.bricktheater.com/",
        "events_url": "https://www.bricktheater.com/",
        "program_label": "Coming up",
        "schedule_type": "event",
        "hours_label": "Open for scheduled events; doors generally open 30 minutes before curtain",
        "admission_label": "Sliding-scale and event-specific tickets; current productions commonly list $25-$50 ranges",
        "visit_source": "https://www.bricktheater.com/visit/",
    },
    {
        "id": "jack-arts",
        "name": "JACK",
        "category": "Community Arts",
        "venue_type": "Performance and community arts space",
        "borough": "Brooklyn",
        "neighborhood": "Clinton Hill",
        "address": "20 Putnam Avenue, Brooklyn, NY 11238",
        "latitude": 40.682608,
        "longitude": -73.961058,
        "description": "A neighborhood arts space connecting experimental performance with community organizing, conversations, music, and artist development.",
        "website": "https://www.jackny.org/",
        "events_url": "https://www.jackny.org/",
        "program_label": "What's on",
        "schedule_type": "event",
        "hours_label": "Open for scheduled performances and community programs",
        "admission_label": "Program-specific admission; recent events include free programs and $15-$20 suggested donations",
        "visit_source": "https://www.jackny.org/visit-us-1",
    },
    {
        "id": "powerhouse-arts",
        "name": "Powerhouse Arts",
        "category": "Art & Exhibitions",
        "venue_type": "Art production center and exhibition venue",
        "borough": "Brooklyn",
        "neighborhood": "Gowanus",
        "address": "322 3rd Avenue, Brooklyn, NY 11215",
        "latitude": 40.676457,
        "longitude": -73.988543,
        "description": "A restored power station where artists fabricate work, gather, and present large-scale public exhibitions and programs.",
        "website": "https://powerhousearts.org/",
        "events_url": "https://powerhousearts.org/calendar",
        "program_label": "Calendar",
        "schedule_type": "regular",
        "hours": weekly(mon=[9, 19.5], tue=[9, 19.5], wed=[9, 19.5], thu=[9, 19.5], fri=[9, 19.5], sat=[10, 18], sun=[10, 18]),
        "hours_label": "Public lobby weekdays 9 AM-7:30 PM and weekends 10 AM-6 PM; exhibition hours may differ",
        "admission_label": "Public lobby access is free; exhibitions and events list any separate admission",
        "adult_price": 0,
        "student_price": 0,
        "visit_source": "https://powerhousearts.org/visit-us",
    },
    {
        "id": "center-for-fiction",
        "name": "The Center for Fiction",
        "category": "Design, Books & Architecture",
        "venue_type": "Literary center, bookstore, and event space",
        "borough": "Brooklyn",
        "neighborhood": "Fort Greene",
        "address": "15 Lafayette Avenue, Brooklyn, NY 11217",
        "latitude": 40.687051,
        "longitude": -73.978589,
        "description": "A public home for readers and writers with a bookstore, cafe, author events, reading groups, workshops, and a members' library.",
        "website": "https://centerforfiction.org/",
        "events_url": "https://centerforfiction.org/events/",
        "program_label": "Upcoming events",
        "schedule_type": "regular",
        "hours": weekly(mon=[9, 20], tue=[9, 20], wed=[9, 20], thu=[9, 20], fri=[9, 20], sat=[9, 20], sun=[9, 20]),
        "hours_label": "Public bookstore and cafe open daily 9 AM-8 PM; event times vary",
        "admission_label": "Public bookstore and cafe entry is free; talks and workshops list separate prices",
        "adult_price": 0,
        "student_price": 0,
        "visit_source": "https://centerforfiction.org/visit/",
    },
    {
        "id": "transit-museum",
        "name": "New York Transit Museum",
        "category": "Museums & Heritage",
        "venue_type": "Transit history museum",
        "borough": "Brooklyn",
        "neighborhood": "Downtown Brooklyn",
        "address": "99 Schermerhorn Street, Brooklyn, NY 11201",
        "latitude": 40.690802,
        "longitude": -73.990001,
        "description": "A museum inside a decommissioned subway station with historic train cars, transit artifacts, design history, and exhibitions about moving New York.",
        "website": "https://www.nytransitmuseum.org/",
        "events_url": "https://www.nytransitmuseum.org/programs/",
        "program_label": "Programs",
        "schedule_type": "regular",
        "hours": weekly(wed=[10, 16], thu=[10, 16], fri=[10, 16], sat=[10, 16], sun=[10, 16]),
        "hours_label": "Wednesday-Sunday 10 AM-4 PM; timed reservations are encouraged",
        "admission_label": "$10 adult / $5 senior, child, or visitor with a disability",
        "adult_price": 10,
        "student_price": 10,
        "visit_source": "https://www.nytransitmuseum.org/know-before-you-visit/",
    },
    {
        "id": "waterfront-museum",
        "name": "Waterfront Museum",
        "category": "Museums & Heritage",
        "venue_type": "Maritime museum and performance barge",
        "borough": "Brooklyn",
        "neighborhood": "Red Hook",
        "address": "290 Conover Street, Brooklyn, NY 11231",
        "latitude": 40.675222,
        "longitude": -74.018337,
        "description": "A floating museum aboard a historic railroad barge interpreting New York Harbor, maritime labor, and waterfront culture through tours and performances.",
        "website": "https://waterfrontmuseum.org/",
        "events_url": "https://waterfrontmuseum.org/events/",
        "program_label": "Upcoming events",
        "schedule_type": "regular",
        "hours": weekly(thu=[16, 20], sat=[13, 17]),
        "hours_label": "Usually Thursday 4-8 PM and Saturday 1-5 PM when the barge is docked",
        "admission_label": "Free public tours; donations support the museum",
        "adult_price": 0,
        "student_price": 0,
        "visit_source": "https://waterfrontmuseum.org/",
    },
    {
        "id": "coney-island-museum",
        "name": "Coney Island Museum",
        "category": "Museums & Heritage",
        "venue_type": "Popular culture and amusement history museum",
        "borough": "Brooklyn",
        "neighborhood": "Coney Island",
        "address": "1208 Surf Avenue, Brooklyn, NY 11224",
        "latitude": 40.575235,
        "longitude": -73.979841,
        "description": "A museum preserving Coney Island's amusement history, vernacular art, performers, architecture, and changing role in New York popular culture.",
        "website": "https://www.coneyislandmuseum.org/",
        "events_url": "https://www.coneyisland.com/",
        "program_label": "Coney Island calendar",
        "schedule_type": "regular",
        "hours": weekly(fri=[12, 17], sat=[12, 17], sun=[12, 17], mon=[12, 17]),
        "hours_label": "Seasonal museum hours Friday-Monday 12-5 PM after July 30; special-event closures are possible",
        "admission_label": "$5 adult / $3 senior, child under 12, or resident of ZIP code 11224",
        "adult_price": 5,
        "student_price": 5,
        "ny_resident_price": 5,
        "visit_source": "https://www.coneyisland.com/visitor-information",
    },
    {
        "id": "wyckoff-house",
        "name": "Wyckoff House Museum",
        "category": "Museums & Heritage",
        "venue_type": "Historic house and community farm",
        "borough": "Brooklyn",
        "neighborhood": "East Flatbush",
        "address": "5816 Clarendon Road, Brooklyn, NY 11203",
        "latitude": 40.644344,
        "longitude": -73.920784,
        "description": "New York City's oldest surviving house, interpreted through Dutch colonial history, migration, farming, family programs, and neighborhood events.",
        "website": "https://wyckoffmuseum.org/",
        "events_url": "https://wyckoffmuseum.org/events/",
        "program_label": "Calendar",
        "schedule_type": "regular",
        "hours": weekly(sat=[11, 14]),
        "hours_label": "Drop-in house tours Saturday 11 AM-2 PM from mid-February through mid-December; grounds have broader seasonal hours",
        "admission_label": "Public house tours are free with donations welcomed",
        "adult_price": 0,
        "student_price": 0,
        "visit_source": "https://wyckoffmuseum.org/visit/",
    },
    {
        "id": "kings-theatre",
        "name": "Kings Theatre",
        "category": "Performance & Music",
        "venue_type": "Historic concert and performance hall",
        "borough": "Brooklyn",
        "neighborhood": "Flatbush",
        "address": "1027 Flatbush Avenue, Brooklyn, NY 11226",
        "latitude": 40.646040,
        "longitude": -73.957348,
        "description": "A restored 1929 movie palace presenting concerts, comedy, dance, family shows, and touring productions for Central Brooklyn audiences.",
        "website": "https://www.kingstheatre.com/",
        "events_url": "https://www.kingstheatre.com/events/",
        "program_label": "Events",
        "schedule_type": "event",
        "hours_label": "Open for scheduled performances; event pages list door and show times",
        "admission_label": "Ticket prices vary by performer, event, and seating section",
        "visit_source": "https://www.kingstheatre.com/box-office/contact-us/",
    },
    {
        "id": "bargemusic-boathouse",
        "name": "Bargemusic at the Boathouse",
        "category": "Performance & Music",
        "venue_type": "Community chamber music series",
        "borough": "Brooklyn",
        "neighborhood": "Brooklyn Heights",
        "address": "Pier 5, Brooklyn Bridge Park, Brooklyn, NY 11201",
        "latitude": 40.695792,
        "longitude": -73.999132,
        "description": "The longtime Brooklyn chamber music series, now presented ashore at the Brooklyn Bridge Park Boathouse with intimate riverfront concerts.",
        "website": "https://www.bargemusic.org/",
        "events_url": "https://www.bargemusic.org/",
        "program_label": "Concert calendar",
        "schedule_type": "event",
        "hours_label": "Open for scheduled concerts, currently concentrated on weekend afternoons",
        "admission_label": "All announced 2026 Boathouse concerts are free",
        "adult_price": 0,
        "student_price": 0,
        "visit_source": "https://www.bargemusic.org/",
    },
    {
        "id": "queens-botanical-garden",
        "name": "Queens Botanical Garden",
        "category": "Community Arts",
        "venue_type": "Botanical garden and cultural landscape",
        "borough": "Queens",
        "neighborhood": "Flushing",
        "address": "43-50 Main Street, Flushing, NY 11355",
        "latitude": 40.751085,
        "longitude": -73.827732,
        "description": "A multilingual community garden connecting plants, ecology, food, migration, seasonal celebrations, public art, and neighborhood culture.",
        "website": "https://queensbotanical.org/",
        "events_url": "https://queensbotanical.org/calendar/",
        "program_label": "Calendar",
        "schedule_type": "regular",
        "hours": weekly(tue=[8, 18], wed=[8, 18], thu=[8, 18], fri=[8, 18], sat=[8, 18], sun=[8, 18]),
        "hours_label": "April-October Tuesday-Sunday 8 AM-6 PM; winter closing is 4:30 PM",
        "admission_label": "$6 adult / $4 student or senior / $2 child from April 1-December 15; free in winter",
        "adult_price": 6,
        "student_price": 4,
        "visit_source": "https://queensbotanical.org/what-to-do-see/",
    },
    {
        "id": "nysci",
        "name": "New York Hall of Science",
        "category": "Museums & Heritage",
        "venue_type": "Interactive science museum",
        "borough": "Queens",
        "neighborhood": "Corona",
        "address": "47-01 111th Street, Corona, NY 11368",
        "latitude": 40.747359,
        "longitude": -73.851695,
        "description": "An interactive science center originating at the 1964 World's Fair, with hands-on exhibitions, design challenges, films, and community learning programs.",
        "website": "https://nysci.org/",
        "events_url": "https://nysci.org/nysci-events",
        "program_label": "Calendar",
        "schedule_type": "regular",
        "hours": weekly(tue=[10, 17], wed=[10, 17], thu=[10, 17], fri=[10, 17], sat=[10, 17], sun=[10, 17]),
        "hours_label": "Tuesday-Sunday 10 AM-5 PM, last entry 4 PM; some experiences close earlier",
        "admission_label": "$22 adult / $19 child, student, or senior; free community hours Friday 2-5 PM with same-day reservation",
        "adult_price": 22,
        "student_price": 19,
        "visit_source": "https://nysci.org/visit/",
    },
    {
        "id": "queens-theatre",
        "name": "Queens Theatre",
        "category": "Performance & Music",
        "venue_type": "Multi-stage performing arts center",
        "borough": "Queens",
        "neighborhood": "Flushing Meadows Corona Park",
        "address": "14 United Nations Avenue South, Corona, NY 11368",
        "latitude": 40.744192,
        "longitude": -73.844412,
        "description": "A borough-focused theater presenting diverse local, national, and international drama, dance, music, comedy, and family programs.",
        "website": "https://www.queenstheatre.org/",
        "events_url": "https://www.queenstheatre.org/",
        "program_label": "What's on",
        "schedule_type": "event",
        "hours_label": "Open for scheduled performances; box office Tuesday-Friday 12-6 PM and two hours before most events",
        "admission_label": "Tickets are priced by production; family, community, and free programs appear alongside paid performances",
        "visit_source": "https://www.queenstheatre.org/our-mission-1mrc",
    },
    {
        "id": "chocolate-factory-theater",
        "name": "The Chocolate Factory Theater",
        "category": "Performance & Music",
        "venue_type": "Experimental dance and performance venue",
        "borough": "Queens",
        "neighborhood": "Long Island City",
        "address": "5-49 49th Avenue, Long Island City, NY 11101",
        "latitude": 40.743739,
        "longitude": -73.954326,
        "description": "An artist-founded incubator for experimental dance, theater, music, video, and interdisciplinary work created through extended residencies.",
        "website": "https://chocolatefactorytheater.org/",
        "events_url": "https://chocolatefactorytheater.org/home",
        "program_label": "Current season",
        "schedule_type": "event",
        "hours_label": "Open for scheduled performances and public programs",
        "admission_label": "Tickets are priced by performance; the venue also presents artist talks and public programs",
        "visit_source": "https://chocolatefactorytheater.org/home",
    },
    {
        "id": "thalia-spanish-theatre",
        "name": "Thalia Spanish Theatre",
        "category": "Performance & Music",
        "venue_type": "Bilingual Latino theater",
        "borough": "Queens",
        "neighborhood": "Sunnyside",
        "address": "41-17 Greenpoint Avenue, Sunnyside, NY 11104",
        "latitude": 40.740324,
        "longitude": -73.923728,
        "description": "A bilingual theater presenting Spanish-language and Latino drama, music, dance, and new work rooted in Queens communities.",
        "website": "https://thaliatheatre.org/",
        "events_url": "https://thaliatheatre.org/buy-tickets/",
        "program_label": "Current productions",
        "schedule_type": "event",
        "hours_label": "Open for scheduled performances; each production lists its curtain time",
        "admission_label": "Ticket prices vary by production and performance date",
        "visit_source": "https://thaliatheatre.org/buy-tickets/",
    },
    {
        "id": "kupferberg-center",
        "name": "Kupferberg Center for the Arts",
        "category": "Performance & Music",
        "venue_type": "College performing arts center",
        "borough": "Queens",
        "neighborhood": "Kew Gardens Hills",
        "address": "65-30 Kissena Boulevard, Flushing, NY 11367",
        "latitude": 40.736190,
        "longitude": -73.816162,
        "description": "Queens College's public arts center, presenting concerts, theater, dance, readings, festivals, and visual art across several campus venues.",
        "website": "https://kupferbergcenter.org/",
        "events_url": "https://kupferbergcenter.org/events/",
        "program_label": "Events",
        "schedule_type": "event",
        "hours_label": "Open for scheduled performances and exhibitions across Queens College venues",
        "admission_label": "Prices vary by event; the calendar also includes free campus and community programs",
        "visit_source": "https://kupferbergcenter.org/",
    },
    {
        "id": "king-manor-museum",
        "name": "King Manor Museum",
        "category": "Museums & Heritage",
        "venue_type": "Historic house and civic history museum",
        "borough": "Queens",
        "neighborhood": "Jamaica",
        "address": "150-03 Jamaica Avenue, Jamaica, NY 11432",
        "latitude": 40.703125,
        "longitude": -73.803769,
        "description": "A historic house exploring Rufus King's antislavery politics, early American life, and Jamaica's civic history through tours and public programs.",
        "website": "https://www.kingmanor.org/",
        "events_url": "https://www.kingmanor.org/",
        "program_label": "Upcoming events",
        "schedule_type": "regular",
        "hours": weekly(tue=[12, 16], wed=[12, 16], thu=[12, 16], fri=[12, 16], sat=[12, 16]),
        "hours_label": "Tuesday-Saturday 12-4 PM with tours on the hour",
        "admission_label": "Suggested admission $5 general / $3 student or senior",
        "adult_price": 5,
        "student_price": 3,
        "visit_source": "https://www.kingmanor.org/",
    },
    {
        "id": "lewis-latimer-house",
        "name": "Lewis Latimer House Museum",
        "category": "Museums & Heritage",
        "venue_type": "Black history and invention museum",
        "borough": "Queens",
        "neighborhood": "Flushing",
        "address": "34-41 137th Street, Flushing, NY 11354",
        "latitude": 40.766757,
        "longitude": -73.829338,
        "description": "The preserved home of African American inventor Lewis H. Latimer, connecting technology, art, writing, family history, and STEAM education.",
        "website": "https://www.lewislatimerhouse.org/",
        "events_url": "https://www.lewislatimerhouse.org/events/",
        "program_label": "Programs",
        "schedule_type": "regular",
        "hours": weekly(fri=[11, 17], sat=[11, 17], sun=[11, 17]),
        "hours_label": "Friday-Sunday 11 AM-5 PM",
        "admission_label": "Self-guided visits are free; guided tours $15 adult / $8 student, senior, veteran, or visitor with a disability",
        "adult_price": 0,
        "student_price": 0,
        "visit_source": "https://www.lewislatimerhouse.org/visit/",
    },
    {
        "id": "voelker-orth-museum",
        "name": "Voelker Orth Museum",
        "category": "Museums & Heritage",
        "venue_type": "Immigrant history house and Victorian garden",
        "borough": "Queens",
        "neighborhood": "Flushing",
        "address": "149-19 38th Avenue, Flushing, NY 11354",
        "latitude": 40.764696,
        "longitude": -73.816113,
        "description": "An 1890s immigrant family home, bird sanctuary, and garden presenting local history, horticulture, exhibitions, workshops, and intimate performances.",
        "website": "https://www.vomuseum.org/",
        "events_url": "https://www.vomuseum.org/events-1",
        "program_label": "Upcoming programs",
        "schedule_type": "regular",
        "hours": weekly(wed=[13, 16], sun=[13, 16]),
        "hours_label": "House tours Wednesday and Sunday 1-4 PM; garden weekdays 10 AM-4 PM and Sunday 12-4 PM",
        "admission_label": "$5 suggested donation for house tours; garden entry is free",
        "adult_price": 5,
        "student_price": 5,
        "visit_source": "https://www.vomuseum.org/hours",
    },
    {
        "id": "queens-farm",
        "name": "Queens County Farm Museum",
        "category": "Museums & Heritage",
        "venue_type": "Historic working farm and cultural landscape",
        "borough": "Queens",
        "neighborhood": "Glen Oaks",
        "address": "73-50 Little Neck Parkway, Queens, NY 11004",
        "latitude": 40.748426,
        "longitude": -73.720186,
        "description": "A 47-acre historic working farm with agricultural interpretation, heritage livestock, seasonal festivals, film nights, tours, and cultural events.",
        "website": "https://www.queensfarm.org/",
        "events_url": "https://www.queensfarm.org/events-calendar/month/",
        "program_label": "Events",
        "schedule_type": "regular",
        "hours": weekly(mon=[10, 17], tue=[10, 17], wed=[10, 17], thu=[10, 17], fri=[10, 17], sat=[10, 17], sun=[10, 17]),
        "hours_label": "Grounds open daily 10 AM-5 PM except listed holidays and ticketed-event changes",
        "admission_label": "Free general admission on most days; special event days may require tickets",
        "adult_price": 0,
        "student_price": 0,
        "visit_source": "https://www.queensfarm.org/visit/",
    },
    {
        "id": "knockdown-center",
        "name": "Knockdown Center",
        "category": "Performance & Music",
        "venue_type": "Large-scale music and art venue",
        "borough": "Queens",
        "neighborhood": "Maspeth",
        "address": "52-19 Flushing Avenue, Maspeth, NY 11378",
        "latitude": 40.715600,
        "longitude": -73.914180,
        "description": "A former industrial complex presenting live music, club programs, experimental performance, outdoor events, and large-scale contemporary art.",
        "website": "https://knockdown.center/",
        "events_url": "https://knockdown.center/",
        "program_label": "Events",
        "schedule_type": "event",
        "hours_label": "Open for scheduled events; each listing provides door and performance times",
        "admission_label": "Ticket prices vary by event and ticket tier",
        "visit_source": "https://knockdown.center/",
    },
    {
        "id": "qed-astoria",
        "name": "Q.E.D. Astoria",
        "category": "Performance & Music",
        "venue_type": "Neighborhood comedy and variety venue",
        "borough": "Queens",
        "neighborhood": "Astoria",
        "address": "27-16 23rd Avenue, Astoria, NY 11105",
        "latitude": 40.775556,
        "longitude": -73.914942,
        "description": "A small neighborhood venue hosting comedy, storytelling, screenings, open mics, classes, readings, and community events almost every night.",
        "website": "https://qedastoria.com/",
        "events_url": "https://qedastoria.com/collections/shows",
        "program_label": "Calendar",
        "schedule_type": "regular",
        "hours": weekly(mon=[17, 23.5], tue=[17, 23.5], wed=[17, 23.5], thu=[17, 23.5], fri=[16, 23.5], sat=[12, 23.5], sun=[12, 23.5]),
        "hours_label": "Opens 5 PM Monday-Thursday, 4 PM Friday, and noon weekends; closes after the final scheduled event",
        "admission_label": "Tickets are priced by event; many small shows and open mics are low-cost",
        "visit_source": "https://qedastoria.com/pages/faqs",
    },
    {
        "id": "secret-theatre-lic",
        "name": "The Secret Theatre",
        "category": "Performance & Music",
        "venue_type": "Independent theater and multidisciplinary arts hub",
        "borough": "Queens",
        "neighborhood": "Long Island City",
        "address": "10-10 44th Avenue, Long Island City, NY 11101",
        "latitude": 40.750018,
        "longitude": -73.950322,
        "description": "An independent theater and arts center combining live productions, youth training, artist studios, exhibitions, workshops, and creative development.",
        "website": "https://www.secrettheatre.com/",
        "events_url": "https://www.secrettheatre.com/",
        "program_label": "What's on",
        "schedule_type": "event",
        "hours_label": "Open for scheduled performances, classes, exhibitions, and workshops",
        "admission_label": "Tickets are priced by production; recent festival tickets have been around $25",
        "visit_source": "https://www.secrettheatre.com/",
    },
    {
        "id": "black-spectrum-theatre",
        "name": "Black Spectrum Theatre",
        "category": "Performance & Music",
        "venue_type": "Black community theater and cultural center",
        "borough": "Queens",
        "neighborhood": "St. Albans",
        "address": "177-01 Baisley Boulevard, Jamaica, NY 11434",
        "latitude": 40.687050,
        "longitude": -73.769464,
        "description": "A long-running Southeast Queens theater presenting Black stories through plays, concerts, films, comedy, education, and socially engaged community programs.",
        "website": "https://www.blackspectrum.com/",
        "events_url": "https://www.blackspectrum.com/",
        "program_label": "Upcoming shows",
        "schedule_type": "event",
        "hours_label": "Open for scheduled performances; box office Monday-Friday 11 AM-6 PM",
        "admission_label": "Tickets are priced by production; recent mainstage plays have been about $35",
        "visit_source": "https://www.blackspectrum.com/",
    },
]


def main():
    existing = json.loads(OUTPUT_PATH.read_text(encoding="utf-8"))
    expansion_ids = {place["id"] for place in EXPANSION}
    merged = [place for place in existing if place["id"] not in expansion_ids]
    merged.extend(EXPANSION)
    OUTPUT_PATH.write_text(
        json.dumps(merged, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(merged)} places ({len(EXPANSION)} outer-borough additions)")


if __name__ == "__main__":
    main()
