from __future__ import annotations

import json
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[1]
SEED_PATH = PROJECT_DIR / "data" / "curated_places.json"


ADDITIONS = [
    {
        "id": "gagosian-west-24",
        "name": "Gagosian West 24th Street",
        "category": "Art & Exhibitions",
        "venue_type": "Contemporary commercial gallery",
        "borough": "Manhattan",
        "neighborhood": "Chelsea",
        "address": "541 West 24th Street, New York, NY 10011",
        "description": "A major Chelsea gallery presenting ambitious exhibitions by leading modern and contemporary artists in a large column-free space.",
        "website": "https://gagosian.com/locations/541-west-24th-street-new-york/",
        "events_url": "https://gagosian.com/exhibitions/archive/?locations=541-west-24th-street-new-york",
        "program_label": "Current exhibitions",
    },
    {
        "id": "gladstone-west-21",
        "name": "Gladstone Gallery",
        "category": "Art & Exhibitions",
        "venue_type": "Contemporary commercial gallery",
        "borough": "Manhattan",
        "neighborhood": "Chelsea",
        "address": "530 West 21st Street, New York, NY 10011",
        "description": "An international contemporary gallery known for artist-led installations and influential experimental practices.",
        "website": "https://www.gladstonegallery.com/contact",
        "events_url": "https://www.gladstonegallery.com/exhibitions",
        "program_label": "Current exhibitions",
    },
    {
        "id": "greene-naftali",
        "name": "Greene Naftali",
        "category": "Art & Exhibitions",
        "venue_type": "Contemporary commercial gallery",
        "borough": "Manhattan",
        "neighborhood": "Chelsea",
        "address": "508 West 26th Street, New York, NY 10001",
        "description": "A Chelsea gallery spanning a ground-floor space and an eighth-floor exhibition room, with a program rooted in conceptually rigorous contemporary art.",
        "website": "https://greenenaftaligallery.com/about",
        "events_url": "https://greenenaftaligallery.com/exhibitions",
        "program_label": "Current exhibitions",
    },
    {
        "id": "kasmin-west-27",
        "name": "Kasmin",
        "category": "Art & Exhibitions",
        "venue_type": "Contemporary commercial gallery",
        "borough": "Manhattan",
        "neighborhood": "Hudson Yards",
        "address": "509 West 27th Street, New York, NY 10001",
        "description": "A skylit gallery for contemporary and historical exhibitions, paired with a rooftop sculpture garden visible from the High Line.",
        "website": "https://www.kasmingallery.com/about-index/visit-us/",
        "events_url": "https://www.kasmingallery.com/exhibitions/",
        "program_label": "Current exhibitions",
    },
    {
        "id": "luhring-augustine-chelsea",
        "name": "Luhring Augustine Chelsea",
        "category": "Art & Exhibitions",
        "venue_type": "Contemporary commercial gallery",
        "borough": "Manhattan",
        "neighborhood": "Chelsea",
        "address": "531 West 24th Street, New York, NY 10011",
        "description": "A long-running New York gallery presenting intergenerational contemporary and historical exhibitions; the Chelsea space currently requests appointments.",
        "website": "https://www.luhringaugustine.com/contact",
        "events_url": "https://www.luhringaugustine.com/exhibitions",
        "program_label": "Current exhibitions",
    },
    {
        "id": "sean-kelly-new-york",
        "name": "Sean Kelly",
        "category": "Art & Exhibitions",
        "venue_type": "Contemporary commercial gallery",
        "borough": "Manhattan",
        "neighborhood": "Hudson Yards",
        "address": "475 Tenth Avenue, New York, NY 10018",
        "description": "A large West Side gallery presenting international contemporary artists across installation, photography, sculpture, painting, and time-based media.",
        "website": "https://www.skny.com/",
        "events_url": "https://www.skny.com/exhibitions",
        "program_label": "Current exhibitions",
    },
    {
        "id": "lehmann-maupin-chelsea",
        "name": "Lehmann Maupin",
        "category": "Art & Exhibitions",
        "venue_type": "Contemporary commercial gallery",
        "borough": "Manhattan",
        "neighborhood": "Chelsea",
        "address": "501 West 24th Street, New York, NY 10011",
        "description": "An international gallery with a multidisciplinary program and a long record of supporting artists working across cultures and media.",
        "website": "https://www.lehmannmaupin.com/about/contact",
        "events_url": "https://www.lehmannmaupin.com/exhibitions",
        "program_label": "Current exhibitions",
    },
    {
        "id": "marianne-boesky-chelsea",
        "name": "Marianne Boesky Gallery",
        "category": "Art & Exhibitions",
        "venue_type": "Contemporary commercial gallery",
        "borough": "Manhattan",
        "neighborhood": "Chelsea",
        "address": "507 West 24th Street, New York, NY 10011",
        "description": "A Chelsea gallery supporting emerging and established artists through painting, sculpture, installation, and research-driven exhibitions.",
        "website": "https://marianneboeskygallery.com/about/",
        "events_url": "https://marianneboeskygallery.com/exhibitions/",
        "program_label": "Current exhibitions",
    },
    {
        "id": "perrotin-new-york",
        "name": "Perrotin New York",
        "category": "Art & Exhibitions",
        "venue_type": "Contemporary commercial gallery",
        "borough": "Manhattan",
        "neighborhood": "Lower East Side",
        "address": "130 Orchard Street, New York, NY 10002",
        "description": "A multi-level Lower East Side gallery presenting international contemporary art alongside editions and artist publications.",
        "website": "https://www.perrotin.com/en/locations/new-york",
        "events_url": "https://www.perrotin.com/en/exhibitions",
        "program_label": "Current exhibitions",
    },
    {
        "id": "uffner-liu",
        "name": "Uffner & Liu",
        "category": "Art & Exhibitions",
        "venue_type": "Contemporary commercial gallery",
        "borough": "Manhattan",
        "neighborhood": "Lower East Side",
        "address": "170 Suffolk Street, New York, NY 10002",
        "description": "A Lower East Side gallery introducing emerging and mid-career artists, with an emphasis on women and internationally rooted practices.",
        "website": "https://uffnerliu.com/contact/",
        "events_url": "https://uffnerliu.com/exhibitions/",
        "program_label": "Current exhibitions",
    },
    {
        "id": "cuchifritos-gallery",
        "name": "Cuchifritos Gallery + Project Space",
        "category": "Community Arts",
        "venue_type": "Nonprofit community gallery",
        "borough": "Manhattan",
        "neighborhood": "Lower East Side",
        "address": "88 Essex Street, New York, NY 10002",
        "description": "A free nonprofit gallery inside Essex Market that commissions emerging and underrepresented artists and brings experimental work into an everyday public setting.",
        "website": "https://www.artistsallianceinc.org/cuchifritos-gallery/",
        "events_url": "https://www.artistsallianceinc.org/exhibitions/",
        "program_label": "Current exhibitions",
    },
    {
        "id": "metropolitan-opera",
        "name": "Metropolitan Opera",
        "category": "Performance & Music",
        "venue_type": "Opera house",
        "borough": "Manhattan",
        "neighborhood": "Lincoln Square",
        "address": "30 Lincoln Center Plaza, New York, NY 10023",
        "description": "New York's principal opera house, presenting large-scale repertory and new productions with orchestra, chorus, singers, designers, and stagecraft under one roof.",
        "website": "https://www.metopera.org/",
        "events_url": "https://www.metopera.org/calendar/",
        "program_label": "Opera calendar",
    },
    {
        "id": "carnegie-hall",
        "name": "Carnegie Hall",
        "category": "Performance & Music",
        "venue_type": "Concert hall",
        "borough": "Manhattan",
        "neighborhood": "Midtown",
        "address": "881 Seventh Avenue, New York, NY 10019",
        "description": "A landmark concert complex presenting orchestras, chamber music, recitals, global traditions, experimental work, and music education across three halls.",
        "website": "https://www.carnegiehall.org/",
        "events_url": "https://www.carnegiehall.org/Calendar",
        "program_label": "Concert calendar",
    },
    {
        "id": "david-geffen-hall",
        "name": "David Geffen Hall",
        "category": "Performance & Music",
        "venue_type": "Concert and performance hall",
        "borough": "Manhattan",
        "neighborhood": "Lincoln Square",
        "address": "10 Lincoln Center Plaza, New York, NY 10023",
        "description": "The home of the New York Philharmonic also hosts contemporary music, film, talks, and Lincoln Center programs in a redesigned public-facing hall.",
        "website": "https://www.lincolncenter.org/venue/david-geffen-hall",
        "events_url": "https://www.lincolncenter.org/venue/david-geffen-hall/v/calendar",
        "program_label": "Current calendar",
    },
    {
        "id": "new-york-city-center",
        "name": "New York City Center",
        "category": "Performance & Music",
        "venue_type": "Dance, musical theater, and performance center",
        "borough": "Manhattan",
        "neighborhood": "Midtown",
        "address": "131 West 55th Street, New York, NY 10019",
        "description": "A historic performance center known for major dance companies, musical theater revivals, artist-led series, and accessible ticket initiatives.",
        "website": "https://www.nycitycenter.org/",
        "events_url": "https://www.nycitycenter.org/events-tickets/",
        "program_label": "Current season",
    },
]


if __name__ == "__main__":
    places = json.loads(SEED_PATH.read_text(encoding="utf-8"))
    additions_by_id = {place["id"]: place for place in ADDITIONS}
    merged = [place for place in places if place["id"] not in additions_by_id]
    merged.extend(ADDITIONS)
    SEED_PATH.write_text(
        json.dumps(merged, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"Wrote {len(merged)} curated places, including {len(ADDITIONS)} expanded Manhattan venues")
